### ISSUE TITLE
Looking good with TipTap 2

### ISSUE THREAD

**Issue by jonassiewertsen** [goldnead/statamic-toc#17]
Hey there

We are working on updating TipTap 2 in Statamic:
https://github.com/statamic/cms/pull/6043

We did test your addon with the new Bard version. As you only do stuff on the PHP side, there shouldn't be any side effects. 

Making sure there aren't, we added the addon to our test repo if you wanna give it a test spin yourself:
https://github.com/spiegeltechlab/statamic-tiptap2-test-repo

Let us know if we did miss something.

**Comment by goldnead** [comment]
Thank you! I think I'm good here, since I got no bard integration on my side, as you already mentioned.
Thanks for the Heads-up, though :)
