### ISSUE TITLE
Heading TOC Modifier does not generate ID's for h4, h5, h6 

### ISSUE THREAD

**Issue by thepalk** [goldnead/statamic-toc#20]
Hello,

I've encountered an issue where the toc Modifier within our project does not generate IDs for headings below h3, specifically for h4, h5, and h6.

Is there a method or setting that can be adjusted to enable ID generation for all heading levels?

Best regards,
Pavlo

**Comment by thepalk** [comment]
Found out that in the parser the max level is set to 3 …

**Comment by goldnead** [comment]
Hey there. As stated in the [Docs](https://github.com/goldnead/statamic-toc#parameters) you can use the parameter `depth` to controle which levels you want to display. 3 is only the default depth being used.
