### ISSUE TITLE
Statamic 5 Support

### ISSUE THREAD

**Issue by janh-kramer** [goldnead/statamic-toc#22]
Hey!
Thanks for your package. Are there any plans to support Statamic v5?

Best Jan

**Comment by janh-kramer** [comment]
Actually I've made a pull request, there are no changes needed, just some little updates, could you please merge it?

**Comment by pdipatrizio** [comment]
I have to be frank, 6+ weeks without a response on such a simple issue is very disappointing for a paid addon.

**Comment by goldnead** [comment]
Sorry, that it took me so long, guys.
Released v1.5. Thanks for the pull request @janh-kramer !

**Comment by binoclard** [comment]
Great, thanks
